import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { createClient, type Session } from '@supabase/supabase-js';
import { ChevronRight, Hotel, LogOut, Menu, Plus, Send, Wifi, Trash2 } from 'lucide-react';
import './styles.css';
import { AvailabilityForm } from './AvailabilityForm';

const API = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api/v1';
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase = supabaseUrl && supabaseAnonKey ? createClient(supabaseUrl, supabaseAnonKey) : null;
type Msg = { role: string; content: string }; type Chat = { id: string; title: string };

function AuthPage({ mode }: { mode: 'login' | 'register' }) {
  const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [success, setSuccess] = useState('');
  if (!supabase) return <AuthShell><p className="error">Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.</p></AuthShell>;
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setError(''); setSuccess(''); if (password.length < 6) return setError('Password must be at least 6 characters.'); setBusy(true); const result = mode === 'login' ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password, options: { data: { full_name: name } } }); setBusy(false); if (result.error) return setError(result.error.message); if (mode === 'register' && !result.data.session) return setSuccess('Registration succeeded. Check your email to confirm the account.'); navigate('/chat'); };
  return <AuthShell><p className="eyebrow">AURELIA HOTEL</p><h1>{mode === 'login' ? 'Welcome back.' : 'Create your account.'}</h1><p className="muted">{mode === 'login' ? 'Sign in to continue your hotel conversation.' : 'Save your hotel conversations and preferences securely.'}</p><form onSubmit={submit}>{mode === 'register' && <input required placeholder="Full name" value={name} onChange={e => setName(e.target.value)} />}<input required type="email" placeholder="Email address" value={email} onChange={e => setEmail(e.target.value)} /><input required type="password" placeholder="Password" value={password} onChange={e => setPassword(e.target.value)} /><button disabled={busy}>{busy ? 'Please wait…' : mode === 'login' ? 'Log in' : 'Create account'}</button></form>{error && <p className="error">{error}</p>}{success && <p className="success">{success}</p>}<p className="tiny">{mode === 'login' ? <>New here? <Link to="/register">Create an account</Link></> : <>Already registered? <Link to="/login">Log in</Link></>}</p></AuthShell>;
}
function AuthShell({ children }: { children: React.ReactNode }) { return <main className="auth"><div className="auth-card"><div className="brand"><Hotel size={26}/><span>Hospira AI</span></div>{children}<p className="tiny">Demo hotel information. No real booking is made.</p></div></main>; }
function Protected({ session, children }: { session: Session | null; children: React.ReactNode }) { return session ? <>{children}</> : <Navigate to="/login" replace />; }
function ChatPage({ session, onLogout }: { session: Session; onLogout: () => void }) {
  const [messages, setMessages] = useState<Msg[]>([]); const [input, setInput] = useState(''); const [chats, setChats] = useState<Chat[]>([]); const [conversation, setConversation] = useState<string | null>(null); const [loading, setLoading] = useState(false); const [mobile, setMobile] = useState(false); const [notice, setNotice] = useState('');
  const call = async (path: string, opts: RequestInit = {}) => { const token = session.access_token; const response = await fetch(API + path, { ...opts, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...(opts.headers || {}) } }); if (response.status === 401) { onLogout(); throw new Error('Your session expired. Please log in again.'); } if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail || 'Request failed.'); } return response.json(); };
  useEffect(() => { call('/conversations').then(setChats).catch(e => setNotice(e.message)); }, []);
  const send = async (text = input) => { if (!text.trim() || loading) return; setInput(''); setNotice(''); setMessages(m => [...m, { role: 'user', content: text }]); setLoading(true); try { const data = await call('/chat/message', { method: 'POST', body: JSON.stringify({ conversation_id: conversation, message: text }) }); setConversation(data.conversation_id); setMessages(m => [...m, { role: 'assistant', content: data.assistant_message }]); setChats(await call('/conversations')); } catch (e: any) { setNotice(e.message); } finally { setLoading(false); } };
  const open = async (id: string) => { try { const data = await call(`/conversations/${id}`); setConversation(id); setMessages(data.messages.filter((m: any) => m.role !== 'system').map((m: any) => ({ role: m.role, content: m.content }))); setMobile(false); } catch (e: any) { setNotice(e.message); } };
  const remove = async (id: string) => { if (!window.confirm('Delete this conversation?')) return; await call(`/conversations/${id}`, { method: 'DELETE' }); setChats(c => c.filter(x => x.id !== id)); if (conversation === id) { setConversation(null); setMessages([]); } };
  return <div className="app"><aside className={mobile ? 'open' : ''}><div className="brand"><Hotel size={23}/><span>Hospira AI</span></div><div className="hotel"><span className="dot"/><div><b>Aurelia Hotel</b><small>Assistant online</small></div></div><button className="new" onClick={() => { setConversation(null); setMessages([]); setMobile(false); }}><Plus size={17}/> New chat</button><div className="history-label">CHAT HISTORY</div>{chats.map(c => <div className={'chat-row ' + (c.id === conversation ? 'active' : '')} key={c.id}><button className="chat-link" onClick={() => open(c.id)}>{c.title}</button><button className="icon-button" aria-label="Delete conversation" onClick={() => remove(c.id)}><Trash2 size={14}/></button></div>)}<div className="side-bottom"><span>{session.user.email}</span><button className="logout" onClick={onLogout}><LogOut size={16}/> Logout</button></div></aside><section className="main"><header><button className="menu" onClick={() => setMobile(!mobile)}><Menu/></button><div><p className="eyebrow">AURELIA HOTEL · HOTEL ASSISTANT</p><h2>How can we help you?</h2></div><div className="header-status"><Wifi size={15}/> Online</div></header><div className="content"><div className="welcome"><p>Ask about rooms, amenities, policies, or demo availability.</p><div className="quick">{['Tell me about the Premium Room', 'Which room is best for a family?', 'What time is breakfast?'].map(q => <button key={q} onClick={() => send(q)}>{q}<ChevronRight size={14}/></button>)}</div></div>{notice && <div className="notice">{notice}</div>}<AvailabilityForm call={call} /><div className="messages">{messages.length === 0 && <div className="empty"><div className="empty-icon"><Hotel size={28}/></div><h3>Your stay starts with a question.</h3><p>I can share grounded hotel information and help compare rooms.</p></div>}{messages.map((m, i) => <div className={'message ' + m.role} key={i}><div className="avatar">{m.role === 'user' ? 'You' : 'H'}</div><div><span className="role">{m.role === 'user' ? 'You' : 'Hospira AI'}</span><p>{m.content}</p></div></div>)}{loading && <div className="message assistant"><div className="avatar">H</div><div><span className="role">Hospira AI</span><p>Thinking…</p></div></div>}</div><div className="composer"><textarea value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); } }} placeholder="Ask about Aurelia Hotel…"/><button onClick={() => send()} disabled={loading || !input.trim()}><Send size={18}/></button><small>Press Enter to send · Shift + Enter for a new line</small></div><p className="disclaimer">Demo hotel information. No real booking is made.</p></div></section></div>;
}
function App() { const [session, setSession] = useState<Session | null>(null); const [ready, setReady] = useState(false); useEffect(() => { if (!supabase) { setReady(true); return; } supabase.auth.getSession().then(({ data }) => { setSession(data.session); setReady(true); }); const { data: listener } = supabase.auth.onAuthStateChange((_event, next) => setSession(next)); return () => listener.subscription.unsubscribe(); }, []); const logout = async () => { await supabase?.auth.signOut(); setSession(null); }; if (!ready) return <div className="loading-screen">Loading Hospira AI…</div>; return <Routes><Route path="/login" element={session ? <Navigate to="/chat" replace /> : <AuthPage mode="login"/>}/><Route path="/register" element={session ? <Navigate to="/chat" replace /> : <AuthPage mode="register"/>}/><Route path="/chat" element={<Protected session={session}><ChatPage session={session!} onLogout={logout}/></Protected>}/><Route path="*" element={<Navigate to={session ? '/chat' : '/login'} replace />}/></Routes>; }
createRoot(document.getElementById('root')!).render(<BrowserRouter><App/></BrowserRouter>);
