import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ChevronRight, Hotel, Menu, Plus, Send, Wifi, Trash2 } from 'lucide-react';
import { AvailabilityForm } from './AvailabilityForm';
import './styles.css';

const API = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api/v1';
const SESSION_KEY = 'hospira_anonymous_session';
const getSessionId = () => { const existing = localStorage.getItem(SESSION_KEY); if (existing) return existing; const created = `${crypto.randomUUID()}-${crypto.randomUUID()}`; localStorage.setItem(SESSION_KEY, created); return created; };
type Msg = { role: string; content: string }; type Chat = { id: string; title: string };

function ChatPage() {
  const [messages, setMessages] = useState<Msg[]>([]); const [input, setInput] = useState(''); const [chats, setChats] = useState<Chat[]>([]); const [conversation, setConversation] = useState<string | null>(null); const [loading, setLoading] = useState(false); const [mobile, setMobile] = useState(false); const [notice, setNotice] = useState('');
  const sessionId = getSessionId();
  const call = async (path: string, opts: RequestInit = {}) => { const response = await fetch(API + path, { ...opts, headers: { 'Content-Type': 'application/json', 'X-Anonymous-Session': sessionId, ...(opts.headers || {}) } }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail || 'Request failed.'); } return response.json(); };
  useEffect(() => { call('/conversations').then(setChats).catch(e => setNotice(e.message)); }, []);
  const send = async (text = input) => { if (!text.trim() || loading) return; setInput(''); setNotice(''); setMessages(m => [...m, { role: 'user', content: text }]); setLoading(true); try { const data = await call('/chat/message', { method: 'POST', body: JSON.stringify({ conversation_id: conversation, message: text }) }); setConversation(data.conversation_id); setMessages(m => [...m, { role: 'assistant', content: data.assistant_message }]); setChats(await call('/conversations')); } catch (e: any) { setNotice(e.message); } finally { setLoading(false); } };
  const open = async (id: string) => { try { const data = await call(`/conversations/${id}`); setConversation(id); setMessages(data.messages.filter((m: any) => m.role !== 'system').map((m: any) => ({ role: m.role, content: m.content }))); setMobile(false); } catch (e: any) { setNotice(e.message); } };
  const remove = async (id: string) => { if (!window.confirm('Delete this conversation?')) return; try { await call(`/conversations/${id}`, { method: 'DELETE' }); setChats(c => c.filter(x => x.id !== id)); if (conversation === id) { setConversation(null); setMessages([]); } } catch (e: any) { setNotice(e.message); } };
  return <div className="app"><aside className={mobile ? 'open' : ''}><div className="brand"><Hotel size={23}/><span>Hospira AI</span></div><div className="hotel"><span className="dot"/><div><b>Aurelia Hotel</b><small>Hotel Assistant</small></div></div><button className="new" onClick={() => { setConversation(null); setMessages([]); setMobile(false); }}><Plus size={17}/> New Chat</button><div className="history-label">CHAT HISTORY</div>{chats.map(c => <div className={'chat-row ' + (c.id === conversation ? 'active' : '')} key={c.id}><button className="chat-link" onClick={() => open(c.id)}>{c.title}</button><button className="icon-button" aria-label="Delete conversation" onClick={() => remove(c.id)}><Trash2 size={14}/></button></div>)}<div className="side-bottom"><span>Public demo session</span><small>Saved in this browser</small></div></aside><section className="main"><header><button className="menu" onClick={() => setMobile(!mobile)}><Menu/></button><div><p className="eyebrow">AURELIA HOTEL · HOTEL ASSISTANT</p><h2>How can we help you?</h2></div><div className="header-status"><Wifi size={15}/> Online</div></header><div className="content"><div className="welcome"><p>Ask about rooms, amenities, policies, or demo availability.</p><div className="quick">{['Tell me about the Premium Room', 'Which room is best for a family?', 'What time is breakfast?'].map(q => <button key={q} onClick={() => send(q)}>{q}<ChevronRight size={14}/></button>)}</div></div>{notice && <div className="notice">{notice}</div>}<AvailabilityForm call={call}/><div className="messages">{messages.length === 0 && <div className="empty"><div className="empty-icon"><Hotel size={28}/></div><h3>Your stay starts with a question.</h3><p>I can share grounded hotel information and help compare rooms.</p></div>}{messages.map((m, i) => <div className={'message ' + m.role} key={i}><div className="avatar">{m.role === 'user' ? 'You' : 'H'}</div><div><span className="role">{m.role === 'user' ? 'You' : 'Hospira AI'}</span><p>{m.content}</p></div></div>)}{loading && <div className="message assistant"><div className="avatar">H</div><div><span className="role">Hospira AI</span><p>Thinking…</p></div></div>}</div><div className="composer"><textarea value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); } }} placeholder="Ask about Aurelia Hotel…"/><button onClick={() => send()} disabled={loading || !input.trim()}><Send size={18}/></button><small>Press Enter to send · Shift + Enter for a new line</small></div><p className="disclaimer">Public demo session. Conversations are saved only in this browser session. No real booking is made.</p></div></section></div>;
}
createRoot(document.getElementById('root')!).render(<ChatPage/>);
