import React,{useEffect,useState} from 'react'; import {createRoot} from 'react-dom/client'; import {Send,Plus,LogOut,Menu,Hotel,Wifi,ChevronRight} from 'lucide-react'; import './styles.css';
const API=import.meta.env.VITE_API_BASE_URL||'http://localhost:8000/api/v1';
type Msg={role:string;content:string}; type Chat={id:string;title:string};
function App(){const [token,setToken]=useState(localStorage.getItem('hospira_token')||''); const [email,setEmail]=useState('guest@aurelia.demo'); const [messages,setMessages]=useState<Msg[]>([]); const [input,setInput]=useState(''); const [chats,setChats]=useState<Chat[]>([]); const [conversation,setConversation]=useState<string|null>(null); const [loading,setLoading]=useState(false); const [mobile,setMobile]=useState(false);
 const call=async(path:string,opts:any={})=>{const r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})}}); if(!r.ok) throw new Error((await r.json()).detail||'Request failed'); return r.json()};
 useEffect(()=>{if(token) call('/conversations').then(setChats).catch(()=>setToken(''));},[token]);
 const send=async(text=input)=>{if(!text.trim()||loading)return; setInput(''); setMessages(m=>[...m,{role:'user',content:text}]); setLoading(true); try{const data=await call('/chat/message',{method:'POST',body:JSON.stringify({conversation_id:conversation,message:text})}); setConversation(data.conversation_id); setMessages(m=>[...m,{role:'assistant',content:data.assistant_message}]); const list=await call('/conversations'); setChats(list);}catch(e:any){setMessages(m=>[...m,{role:'assistant',content:e.message||'Something went wrong. Please try again.'}]);}finally{setLoading(false)}};
 const open=async(id:string)=>{const d=await call('/conversations/'+id);setConversation(id);setMessages(d.messages.map((m:any)=>({role:m.role,content:m.content})));setMobile(false)};
 if(!token)return <main className="auth"><div className="auth-card"><div className="brand"><Hotel size={26}/><span>Hospira AI</span></div><p className="eyebrow">AURELIA HOTEL</p><h1>Hotel help, made simple.</h1><p className="muted">Connect your Supabase session to use the assistant. For local preview, paste a valid JWT below.</p><input placeholder="Supabase access token" value={token} onChange={e=>setToken(e.target.value)}/><button onClick={()=>{localStorage.setItem('hospira_token',token)}}>Continue to Hospira AI</button><p className="tiny">Demo hotel information. No real booking is made.</p></div></main>;
 return <div className="app"><aside className={mobile?'open':''}><div className="brand"><Hotel size={23}/><span>Hospira AI</span></div><div className="hotel"><span className="dot"></span><div><b>Aurelia Hotel</b><small>Assistant online</small></div></div><button className="new" onClick={()=>{setConversation(null);setMessages([]);setMobile(false)}}><Plus size={17}/> New chat</button><div className="history-label">CHAT HISTORY</div>{chats.map(c=><button className={'chat-link '+(c.id===conversation?'active':'')} key={c.id} onClick={()=>open(c.id)}>{c.title}</button>)}<div className="side-bottom"><span>{email}</span><button className="logout" onClick={()=>{localStorage.removeItem('hospira_token');setToken('')}}><LogOut size={16}/> Log out</button></div></aside><section className="main"><header><button className="menu" onClick={()=>setMobile(!mobile)}><Menu/></button><div><p className="eyebrow">AURELIA HOTEL · HOTEL ASSISTANT</p><h2>How can we help you?</h2></div><div className="header-status"><Wifi size={15}/> Online</div></header><div className="content"><div className="welcome"><p>Ask about rooms, amenities, policies, or demo availability.</p><div className="quick">{['Tell me about the Premium Room','Which room is best for a family?','What time is breakfast?'].map(q=><button key={q} onClick={()=>send(q)}>{q}<ChevronRight size={14}/></button>)}</div></div><div className="messages">{messages.length===0&&<div className="empty"><div className="empty-icon"><Hotel size={28}/></div><h3>Your stay starts with a question.</h3><p>I can share grounded hotel information and help compare rooms.</p></div>}{messages.map((m,i)=><div className={'message '+m.role} key={i}><div className="avatar">{m.role==='user'?'You':'H'}</div><div><span className="role">{m.role==='user'?'You':'Hospira AI'}</span><p>{m.content}</p></div></div>)}{loading&&<div className="message assistant"><div className="avatar">H</div><div><span className="role">Hospira AI</span><p className="typing">Thinking<span>.</span><span>.</span><span>.</span></p></div></div>}</div><div className="composer"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ask about Aurelia Hotel..."/><button onClick={()=>send()} disabled={loading||!input.trim()}><Send size={18}/></button><small>Press Enter to send · Shift + Enter for a new line</small></div><p className="disclaimer">Demo hotel information. No real booking is made.</p></div></section></div>}
createRoot(document.getElementById('root')!).render(<App/>);